- name: Testing
  shell: hostname
  register: output
- debug: 
    msg: "{{ output.stdout }}"
- name: Install LAMP Dependency
  yum: name={{ item }} state=present
  with_items:
     - httpd
     - mariadb-server
     - mariadb
     - php
     - php-mysql
     - php-fpm 
- name: start the web server
  systemd: state=started name=httpd enabled=true
- name: start the mariadb  
  systemd: state=started name=mariadb enabled=true
  
- name: Versions check for LAMP 
  command: php --version && mysql --version && httpd --version
  register: version
- debug: 
    msg: "{{ version.stdout }}"
