- name: Install LAMP Dependency
  yum: name={{ item }} state=present
  with_items:
     - httpd
     - mariadb-server
     - mariadb
     - php
     - php-mysql
     - php-fpm
     - php-intl
     - php-gd
     - php-xml
     - texlive
     - epel-release
     - php-xcache

- name: Versions check for LAMP
  template: src=php.j2 dest=/var/www/html/
  register: version
  notify:
    - restart httpd

- debug:
    msg: "{{ version.stdout }}"
